const notificationListActionTypes = {
  RESETED: 'NOTIFICATION_LIST_RESETED',
  TOGGLE_ONE_SELECTED: 'NOTIFICATION_LIST_TOGGLE_ONE_SELECTED',
  TOGGLE_ALL_SELECTED: 'NOTIFICATION_LIST_TOGGLE_ALL_SELECTED',
  CLEAR_ALL_SELECTED: 'NOTIFICATION_LIST_CLEAR_ALL_SELECTED',
  PAGINATION_CHANGED: 'NOTIFICATION_LIST_PAGINATION_CHANGED',
  SORTER_CHANGED: 'NOTIFICATION_LIST_SORTER_CHANGED',

  FETCH_STARTED: 'NOTIFICATION_LIST_FETCH_STARTED',
  FETCH_SUCCESS: 'NOTIFICATION_LIST_FETCH_SUCCESS',
  FETCH_ERROR: 'NOTIFICATION_LIST_FETCH_ERROR',

  EXPORT_STARTED: 'NOTIFICATION_LIST_EXPORT_STARTED',
  EXPORT_SUCCESS: 'NOTIFICATION_LIST_EXPORT_SUCCESS',
  EXPORT_ERROR: 'NOTIFICATION_LIST_EXPORT_ERROR',

  COUNT_STARTED: 'NOTIFICATION_LIST_COUNT_STARTED',
  COUNT_SUCCESS: 'NOTIFICATION_LIST_COUNT_SUCCESS',
  COUNT_ERROR: 'NOTIFICATION_LIST_COUNT_ERROR',

  CREATE_STARTED: `NOTIFICATION_CREATE_STARTED`,
  CREATE_SUCCESS: `NOTIFICATION_CREATE_SUCCESS`,
  CREATE_ERROR: `NOTIFICATION_CREATE_ERROR`,


};

export default notificationListActionTypes;
