import Permissions from 'src/security/permissions';
import { i18n } from 'src/i18n';
import config from 'src/config';

const permissions = Permissions.values;

export default [
  {
    id: '0',
    path: '/',
    exact: true,
    icon: 'fas fa-chart-line',
    label: i18n('dashboard.dashboard'),
    className: 'menu-li side-menue',
    permissionRequired: permissions.categoryRead,
  },
  {
    id: '0',
    path: '/clients',
    exact: true,
    icon: 'fas fa-user-friends',
    label: i18n('dashboard.clients'),
    className: 'menu-li side-menue',
    permissionRequired: permissions.categoryRead,
  },
  {
    id: '0',
    path: '/settings/wallet',
    exact: true,
    icon: 'fas fa-wallet',
    label: i18n('dashboard.settings'),
    className: 'menu-li side-menue',
    permissionRequired: permissions.userRead,
  },
  {
    id: '0',
    path: '/category',
    exact: true,
    icon: 'fas fa-headset',
    label: i18n('dashboard.customersupport'),
    className: 'menu-li side-menue',
    permissionRequired: permissions.categoryRead,
  },
  {
    id: '0',
    path: '/vip',
    exact: true,
    icon: 'fas fa-crown',
    label: i18n('dashboard.Level'),
    className: 'menu-li side-menue',
    permissionRequired: permissions.categoryRead,
  },

  {
    id: '0',
    path: '/deposit',
    exact: true,
    icon: 'fas fa-arrow-down',
    label: i18n('dashboard.deposit'),
    className: 'menu-li side-menue',
    permissionRequired: permissions.categoryRead,
  },
  {
    id: '0',
    path: '/withdraw',
    exact: true,
    icon: 'fas fa-arrow-up',
    label: i18n('dashboard.withdraw'),
    className: 'menu-li side-menue',
    permissionRequired: permissions.categoryRead,
  },
    {
    id: '0',
    path: '/transaction',
    exact: true,
    icon: 'fas fa-exchange-alt',
    label: i18n('dashboard.transaction'),
    className: 'menu-li side-menue',
    permissionRequired: permissions.categoryRead,
  },
  {
    id: '0',
    path: '/record',
    exact: true,
    icon: 'fas fa-clipboard-list',
    label: i18n('dashboard.record'),
    className: 'menu-li side-menue',
    permissionRequired: permissions.categoryRead,
  },
  {
    id: '0',
    path: '/product',
    exact: true,
    icon: 'fas fa-tshirt',
    label: i18n('dashboard.product'),
    className: 'menu-li side-menue',
    permissionRequired: permissions.categoryRead,
  },
  {
    id: '0',
    path: '/user',
    exact: true,
    icon: 'fas fa-user-cog',
    label: i18n('dashboard.worker'),
    className: 'menu-li side-menue',
    permissionRequired: permissions.userRead,
  },
].filter(Boolean);